import { useState, useEffect } from 'react'
import { FileText, Clock, AlertTriangle, Shield, Users, RefreshCw, Search, Zap, ExternalLink } from 'lucide-react'
import { Link, useLocation } from 'react-router-dom'
import { getPostmortems, type Postmortem } from '../services/api'

export default function Postmortems() {
  const [postmortems, setPostmortems] = useState<Postmortem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [selectedPm, setSelectedPm] = useState<Postmortem | null>(null)
  const [search, setSearch] = useState('')
  const location = useLocation()

  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await getPostmortems()
        setPostmortems(data || [])
        // Check for ?incident= in URL
        const params = new URLSearchParams(location.search)
        const incidentId = params.get('incident')
        if (incidentId && data && data.length > 0) {
          setSearch(incidentId)
          const match = data.find(pm => pm.incidentId === incidentId || pm.incidentId?.toLowerCase() === incidentId.toLowerCase())
          if (match) setSelectedPm(match)
          else setSelectedPm(data[0])
        } else if (data && data.length > 0) {
          setSelectedPm(data[0])
        }
      } catch (err) {
        console.error('Postmortems fetch error:', err)
        setError(err instanceof Error ? err.message : 'Failed to load postmortems')
        setPostmortems([])
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  const filtered = postmortems.filter(pm => {
    if (!search) return true
    const q = search.toLowerCase()
    const title = String(pm.title || '').toLowerCase()
    const service = String(pm.service || '').toLowerCase()
    const incidentId = String(pm.incidentId || '').toLowerCase()
    const rootCause = String(pm.rootCause || '').toLowerCase()
    const impact = String(pm.impactSummary || '').toLowerCase()
    return title.includes(q) ||
      service.includes(q) ||
      incidentId.includes(q) ||
      rootCause.includes(q) ||
      impact.includes(q)
  })

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <RefreshCw className="w-6 h-6 text-blue-500 animate-spin" />
      </div>
    )
  }

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">Postmortems</h2>
          <p className="text-sm text-gray-500 mt-1">AI-generated incident analysis & prevention recommendations</p>
        </div>
        <span className="px-3 py-1.5 bg-[#161b22] border border-gray-800 rounded-lg text-xs text-gray-400 font-medium">
          {filtered.length} reports
        </span>
      </div>

      {error && (
        <div className="p-3 bg-red-950/50 border border-red-800 rounded-lg text-sm text-red-300">{error}</div>
      )}

      {filtered.length === 0 ? (
        <div className="bg-[#161b22] border border-gray-800 rounded-xl p-12 text-center">
          <FileText className="w-10 h-10 text-gray-600 mx-auto mb-3" />
          <p className="text-gray-400">No postmortems found</p>
          <p className="text-xs text-gray-500 mt-1">Postmortems are auto-generated by Bedrock AI after each incident</p>
        </div>
      ) : (
        <div className="flex gap-5 h-[calc(100vh-100px)]">
          {/* Left Panel — List */}
          <div className="w-80 flex-shrink-0 flex flex-col">
            {/* Search */}
            <div className="relative mb-3">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
              <input
                type="text"
                placeholder="Search..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full pl-9 pr-3 py-2 bg-[#161b22] border border-gray-800 rounded-lg text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-600 transition-colors"
              />
            </div>

            {/* List */}
            <div className="flex-1 overflow-y-auto space-y-1 pr-1">
              {filtered.map(pm => (
                <button
                  key={pm.id}
                  onClick={() => setSelectedPm(pm)}
                  className={`w-full text-left px-3 py-3 rounded-lg transition-all ${
                    selectedPm?.id === pm.id
                      ? 'bg-blue-900/20 border border-blue-800/40'
                      : 'hover:bg-gray-800/40 border border-transparent'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <div className={`w-2 h-2 rounded-full flex-shrink-0 ${
                      pm.severity >= 4 ? 'bg-red-500' : pm.severity >= 3 ? 'bg-orange-500' : 'bg-yellow-500'
                    }`} />
                    <span className="text-sm font-medium text-white truncate">
                      {pm.service === 'service' || pm.service === 'unknown' ? pm.incidentId : pm.service}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 mt-1 ml-4.5 pl-[18px]">
                    <span className="text-[10px] text-blue-400 font-mono">{pm.incidentId}</span>
                    <span className="text-[10px] text-gray-600">·</span>
                    <span className="text-[10px] text-gray-500">{pm.resolvedAt ? new Date(pm.resolvedAt).toLocaleDateString() : '—'}</span>
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Right Panel — Detail */}
          <div className="flex-1 bg-[#161b22] border border-gray-800 rounded-xl overflow-y-auto">
            {selectedPm ? (
              <div className="p-6">
                {/* Header */}
                <div className="flex items-start justify-between mb-6">
                  <div>
                    <h3 className="text-lg font-semibold text-white">
                      {selectedPm.service === 'service' || selectedPm.service === 'unknown'
                        ? selectedPm.incidentId
                        : selectedPm.service}
                    </h3>
                    <p className="text-sm text-gray-400 mt-0.5">
                      {selectedPm.title?.includes('Postmortem: service') || selectedPm.title?.includes('Postmortem: unknown')
                        ? `Incident Postmortem — ${selectedPm.incidentId}`
                        : selectedPm.title || 'Incident Postmortem Report'}
                    </p>
                  </div>
                  <Link
                    to={`/incidents/${selectedPm.incidentId}`}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-900/20 border border-blue-800/40 rounded-lg text-xs text-blue-400 hover:bg-blue-900/30 transition-colors"
                  >
                    <ExternalLink className="w-3 h-3" />
                    View Incident
                  </Link>
                </div>

                {/* Meta Row */}
                <div className="flex flex-wrap items-center gap-3 mb-6 pb-5 border-b border-gray-800/60">
                  <SevBadge severity={selectedPm.severity} />
                  <span className="text-xs text-blue-400 font-mono bg-blue-900/15 px-2 py-1 rounded">{selectedPm.incidentId}</span>
                  <span className="text-xs text-gray-400 flex items-center gap-1.5 bg-gray-800/40 px-2 py-1 rounded">
                    <Clock className="w-3 h-3" />
                    {selectedPm.duration}
                  </span>
                  <span className="text-xs text-gray-500">
                    {selectedPm.resolvedAt ? new Date(selectedPm.resolvedAt).toLocaleString() : ''}
                  </span>
                </div>

                {/* Summary */}
                {(selectedPm.summary || selectedPm.impactSummary) && (
                  <div className="mb-5 p-4 bg-gray-900/60 rounded-lg border-l-4 border-blue-600">
                    <p className="text-sm text-gray-200 leading-relaxed">{selectedPm.summary || selectedPm.impactSummary}</p>
                  </div>
                )}

                {/* Root Cause */}
                <div className="mb-5">
                  <div className="flex items-center gap-2 mb-3">
                    <div className="w-7 h-7 rounded-lg bg-orange-900/25 flex items-center justify-center">
                      <AlertTriangle className="w-4 h-4 text-orange-400" />
                    </div>
                    <h4 className="text-sm font-semibold text-white">Root Cause</h4>
                  </div>
                  <p className="text-sm text-gray-300 leading-relaxed pl-9">{selectedPm.rootCause || 'Analysis pending'}</p>
                </div>

                {/* Impact — only show if it has real data, not placeholder */}
                {selectedPm.impactSummary && selectedPm.impactSummary !== selectedPm.summary &&
                 !selectedPm.impactSummary.includes('Revenue at risk: Unknown') && (
                  <div className="mb-5">
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-7 h-7 rounded-lg bg-blue-900/25 flex items-center justify-center">
                        <Users className="w-4 h-4 text-blue-400" />
                      </div>
                      <h4 className="text-sm font-semibold text-white">Impact</h4>
                    </div>
                    <div className="pl-9 flex flex-wrap gap-3">
                      {selectedPm.impactSummary.split(' · ').map((part, i) => (
                        <span key={i} className="px-3 py-1.5 rounded-lg bg-gray-800/60 border border-gray-700/40 text-sm text-gray-300">
                          {part}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Scoring Reasoning */}
                {selectedPm.scoringReasoning && (
                  <div className="mb-5">
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-7 h-7 rounded-lg bg-purple-900/25 flex items-center justify-center">
                        <Zap className="w-4 h-4 text-purple-400" />
                      </div>
                      <h4 className="text-sm font-semibold text-white">Scoring Reasoning</h4>
                    </div>
                    <p className="text-sm text-gray-300 leading-relaxed pl-9 whitespace-pre-wrap">{selectedPm.scoringReasoning}</p>
                  </div>
                )}

                {/* Prevention */}
                {selectedPm.prevention && Array.isArray(selectedPm.prevention) && selectedPm.prevention.length > 0 && (
                  <div className="mb-5">
                    <div className="flex items-center gap-2 mb-4">
                      <div className="w-7 h-7 rounded-lg bg-green-900/25 flex items-center justify-center">
                        <Shield className="w-4 h-4 text-green-400" />
                      </div>
                      <h4 className="text-sm font-semibold text-white">Prevention Recommendations</h4>
                    </div>
                    <div className="space-y-3 pl-9">
                      {selectedPm.prevention.map((step, i) => (
                        <div key={i} className="flex items-start gap-3">
                          <span className="flex-shrink-0 w-6 h-6 bg-green-900/20 border border-green-800/30 rounded-md flex items-center justify-center text-xs text-green-400 font-bold mt-0.5">
                            {i + 1}
                          </span>
                          <p className="text-sm text-gray-300 leading-relaxed">{step}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Footer */}
                <div className="flex items-center gap-2 pt-4 border-t border-gray-800/40">
                  <Zap className="w-3.5 h-3.5 text-gray-600" />
                  <span className="text-xs text-gray-600">Generated by Amazon Bedrock AI</span>
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-center h-full">
                <p className="text-sm text-gray-500">Select a postmortem to view details</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

function SevBadge({ severity }: { severity: number }) {
  const config: Record<number, { label: string; classes: string }> = {
    5: { label: 'SEV-5 Critical', classes: 'bg-red-950/60 text-red-300 border-red-800/50' },
    4: { label: 'SEV-4 High', classes: 'bg-red-950/40 text-red-300 border-red-800/40' },
    3: { label: 'SEV-3 Medium', classes: 'bg-orange-950/40 text-orange-300 border-orange-800/40' },
    2: { label: 'SEV-2 Low', classes: 'bg-yellow-950/40 text-yellow-300 border-yellow-800/40' },
    1: { label: 'SEV-1 Info', classes: 'bg-green-950/40 text-green-300 border-green-800/40' }
  }
  const c = config[severity] || config[3]
  return <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold border ${c.classes} uppercase tracking-wide`}>{c.label}</span>
}
